# -*- coding: utf-8 -*-
"""Week_5_SQL_Muder_Mystery(SAI VARMA).ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1q4px6KdsUyz10aqDU-alpdEiu0FUm_pb

- Importing Libraries
"""

import pandas as pd
import sqlite3 as sql

"""- Establishing connection"""

conn = sql.connect("/content/drive/MyDrive/Internship Projects/Week-5/sql-murder-mystery.db")

conn

query_1 = """
SELECT DISTINCT type FROM crime_scene_report;
"""
pd.read_sql_query(query_1, conn)

query_2 = """
SELECT *
FROM crime_scene_report
WHERE city = "SQL City" AND type = 'murder'
ORDER BY date;
"""

pd.set_option('display.max_colwidth',None)

pd.read_sql_query(query_2,conn)

"""- Getting details of Witness-1"""

query_3 = """
SELECT *
FROM person
WHERE address_street_name =  "Northwestern Dr"
ORDER BY address_number DESC
LIMIT 1;
"""
pd.set_option('display.max_colwidth',None)

pd.read_sql_query(query_3,conn)

"""- Getting Details of Witness-2"""

query_4 = """
SELECT *
FROM person
WHERE address_street_name =  "Franklin Ave"
AND name LIKE "%Annabel%";
"""
pd.set_option('display.max_colwidth',None)

pd.read_sql_query(query_4,conn)

"""- Interviews of Two Witnesses"""

query_5 = """
SELECT *
FROM interview
WHERE person_id IN (14887,16371);
"""
pd.set_option('display.max_colwidth',None)

pd.read_sql_query(query_5,conn)

"""#Finding Killer based on clues got from Interviews"""

query_6 = """
SELECT p.id,p.name,dl.gender,p.license_id,gfc.membership_id,dl.plate_number,gfc.check_in_date,gfn.membership_start_date,gfn.membership_status  FROM person as p

INNER JOIN drivers_license as dl on dl.id = p.license_id
INNER JOIN get_fit_now_member as gfn on p.id = gfn.person_id
INNER JOIN get_fit_now_check_in as gfc on gfc.membership_id = gfn.id

WHERE plate_number LIKE '%H42W%' AND gender = 'male' AND membership_status = 'gold'
AND gfn.id LIKE '48Z%';
"""
pd.set_option('display.max_colwidth',None)

pd.read_sql_query(query_6,conn)

"""#Found the Killer"""

cursor = conn.cursor()

query_7 = """
INSERT INTO solution VALUES (1,'Jeremy Bowers');
"""

count = cursor.execute(query_7)
conn.commit()

query_8 = """
SELECT value FROM solution;
"""
pd.read_sql_query(query_8,conn)

query_9 = """
SELECT *
FROM interview
WHERE person_id = 67318  ;
"""
pd.set_option('display.max_colwidth',None)

pd.read_sql_query(query_9,conn)

"""# Found the Master Mind of this Mystery - Miranda Priestly"""

query_10 = """
SELECT p.*,dl.car_make, dl.car_model, dl.hair_color, dl.height, inc.annual_income, fec.event_name
FROM person as p

INNER JOIN income as inc on inc.ssn = p.ssn
INNER JOIN drivers_license as dl on dl.id = p.license_id
INNER JOIN facebook_event_checkin as fec on p.id = fec.person_id

WHERE gender = 'female' AND car_make = 'Tesla' AND car_model = 'Model S'
AND hair_color = 'red';
"""
pd.set_option('display.max_colwidth',None)

pd.read_sql_query(query_10,conn)

cursor = conn.cursor()

query_11 = """
INSERT INTO solution VALUES (1,'Miranda Priestly');
"""

count = cursor.execute(query_11)
conn.commit()

query_12 = """
SELECT value FROM solution;
"""
pd.set_option('display.max_colwidth',None)
pd.read_sql_query(query_12,conn)